Repository usecannon/cannon, pull requests merged in 2024-12, with the labels that each got.

#1573 fix(builder): reduce the amount of checks that happen by default on chain definition
  packages/builder/src/actions.ts
  packages/builder/src/builder.test.ts
  packages/builder/src/builder.ts
  packages/builder/src/definition.test.ts
  packages/builder/src/definition.ts
  packages/builder/src/package-reference.ts
  packages/builder/src/steps/clone.ts
  packages/builder/src/util.test.ts
  packages/builder/src/util.ts
Labels: bug

#1582 fix(builder): Disable extraneous check
  packages/builder/src/definition.ts
  packages/website/postcss.config.js
  packages/website/tailwind.config.js
Labels: bug

#1583 fix(website): rendering interact values
  packages/website/src/features/Packages/FunctionOutput.tsx
Labels: bug

#1584 fix(website): deployment page rewrite
  packages/website/serve.json
  packages/website/vercel.json
Labels: bug

#1576 fix(website): copy button component
  packages/website/src/components/ClipboardButton.tsx
  packages/website/src/features/Deploy/DisplayedTransaction.tsx
Labels: bug

#1592 fix(website): add links
  packages/website/guides/setup.mdx
  packages/website/src/components/ui/tooltip.tsx
  packages/website/src/features/Search/PackageCard/DataTable.tsx
Labels: documentation

#1600 fix(website): fix well-formatted hex
  packages/website/src/features/Packages/FunctionInput.tsx
  packages/website/src/features/Packages/FunctionInput/ByteInput.tsx
  packages/website/src/features/Packages/FunctionInput/DefaultInput.tsx
Labels: bug

#1567 feat(cli): ability to print many different types of data with inspect
  packages/cli/src/commands/config/index.ts
  packages/cli/src/commands/inspect.test.ts
  packages/cli/src/commands/inspect.ts
  packages/cli/src/index.ts
  packages/cli/src/write-script/render-foundry.ts
Labels: enhancement
