Repository usecannon/cannon, pull requests merged in 2024-11, with the labels that each got.

#1483 chore(cli): refactor `configureSigners` function
  packages/cli/src/commands/config/index.ts
  packages/cli/src/util/build.ts
Labels: chore

#1529 fix(cli): cannot build on Cannon network with --dry-run
  packages/cli/src/index.ts
Labels: bug

#1548 feat(lsp): add lsp project
  packages/lsp/.gitignore
  packages/lsp/Dockerfile
  packages/lsp/package.json
  packages/lsp/scripts/generateSchema.js
  packages/lsp/src/schema.json
  packages/lsp/tsconfig.build.json
  packages/lsp/tsconfig.json
Labels: enhancement

#1550 fix(links-guides): fix links to /setup and add test solidity file
  packages/website/guides/test-with-cannon.mdx
  packages/website/src/features/Docs/DocsLandingPage.tsx
  packages/website/src/features/HomePage/HomePage.tsx
  packages/website/src/pages/learn/guides/index.tsx
Labels: bug, documentation

#1536 feat(cli): add render foundry script
  packages/cli/src/write-script/render-cast.ts
  packages/cli/src/write-script/render-foundry.ts
Labels: enhancement
